name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: python3 01/sonar_sweep.py --inputs 01/inputs.txt --window 3 | grep 1486
